{"metadata": {"dbt_schema_version": "https://schemas.getdbt.com/dbt/run-results/v5.json", "dbt_version": "1.7.2", "generated_at": "2024-01-13T12:26:52.062194Z", "invocation_id": "ab744ea0-5c4b-4849-92f1-6aac579308e5", "env": {}}, "results": [{"status": "error", "timing": [{"name": "compile", "started_at": "2024-01-13T12:26:52.008909Z", "completed_at": "2024-01-13T12:26:52.014950Z"}, {"name": "execute", "started_at": "2024-01-13T12:26:52.015897Z", "completed_at": "2024-01-13T12:26:52.048400Z"}], "thread_id": "Thread-1 (worker)", "execution_time": 0.043358564376831055, "adapter_response": {}, "message": "Database Error in model customer_order (models/customer_order.sql)\n  relation \"customers\" does not exist\n  LINE 10: FROM customers cu\n                ^\n  compiled Code at target/run/oms_dbt_proj/models/customer_order.sql", "failures": null, "unique_id": "model.oms_dbt_proj.customer_order", "compiled": true, "compiled_code": "SELECT\n  co.*,\n  cu.*\nFROM customers cu\nJOIN orders co ON cu.customer_id = co.customer_id", "relation_name": "\"postgres\".\"postgres\".\"customer_order\""}], "elapsed_time": 0.14928603172302246, "args": {"defer": false, "vars": {}, "project_dir": "/usr/app/dbt", "use_colors": true, "log_level": "info", "use_colors_file": true, "profiles_dir": "/usr/app/dbt", "partial_parse_file_diff": true, "warn_error_options": {"include": [], "exclude": []}, "which": "run", "invocation_command": "dbt run", "write_json": true, "macro_debugging": false, "indirect_selection": "eager", "strict_mode": false, "printer_width": 80, "log_format_file": "debug", "favor_state": false, "log_path": "/usr/app/dbt/logs", "quiet": false, "partial_parse": true, "show_resource_report": false, "version_check": true, "cache_selected_only": false, "static_parser": true, "exclude": [], "log_format": "default", "print": true, "select": [], "log_level_file": "debug", "introspect": true, "populate_cache": true, "enable_legacy_logger": false, "send_anonymous_usage_stats": true, "log_file_max_bytes": 10485760}}